myenv/kebapbuilder/kebapbuilder/urls.py
from django.urls import path

from . import views

app_name = 'kebapbuilder'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('add/', views.AddView.as_view(), name='add'),
]

myenv/kebapbuilder/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('kebapbuilder/', include('kebapbuilder.urls')),
]

myenv/kebapbuilder/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

myenv/kebapbuilder/kebapbuilder/models.py
from django.db import models

from django.contrib import admin

# Create your models here.
class Person(models.Model):
    first_name = models.CharField(max_length=70)
    last_name = models.CharField(max_length=70)

    def __str__(self):
        return self.firstname + ' ' + self.lastname

class Additional(models.Model):
    additional_name = models.CharField(max_length=70)
    additional_price = models.FloatField(default=0)

    def __str__(self):
        return f'{self.additional_name} ({self.additional_price}€)'

class MainType(models.Model):
    main_type_name = models.CharField(max_length=70)
    main_type_price = models.FloatField(default=0)

    def __str__(self):
        return f'{self.main_type_name} ({self.main_type_price}€)'

class Type(models.Model):
    type_name = models.CharField(max_length=70)
    type_price = models.FloatField(default=0)

    def __str__(self):
        return f'{self.type_name} ({self.type_price}€)'

class Order(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    type = models.ForeignKey(Type, on_delete=models.CASCADE)
    main_type = models.ForeignKey(MainType, on_delete=models.CASCADE)
    additionals = models.ManyToManyField(Additional)
    is_ordered = models.BooleanField(default=False)
    order_date = models.DateField(default=None, blank=True)

myenv/kebapbuilder/polls/models.py
import datetime

from django.db import models
from django.utils import timezone

from django.contrib import admin

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text
    
    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published recently?'
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self) -> str:
        return self.choice_text

myenv/kebapbuilder/kebapbuilder/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

# Create your views here.
from kebapbuilder.models import Order, Type, MainType, Additional, Person

class IndexView(generic.ListView):
    template_name = 'kebapbuilder/order_list.html'
    context_object_name = 'order_list'

    def get_queryset(self):
        return Order.objects.order_by('-person')
    
class AddView(generic.CreateView):
    model = Order
    fields = ['person', 'type', 'main_type', 'additionals']
    template_name = 'kebapbuilder/order_detail.html'

myenv/kebapbuilder/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from polls.models import Question, Choice

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())
    
class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

myenv/kebapbuilder/kebapbuilder/templates/kebapbuilder/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta http-equiv="x-ua-compatible" content="ie=edge" />
        <title>{% block title %}{% endblock %}</title>
        <!-- MDB icon -->
        <link rel="icon" href="{% static 'img/mdb-favicon.ico' %}" type="image/x-icon" />
        <!-- Font Awesome -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />
        <!-- Google Fonts Roboto -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" />
        <!-- MDB -->
        <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}" />
    </head>
    <body>
        <!-- Start your project here-->
        <div class="container">
            <div class="row mt-2">
                <div class="col-lg-12">
                    {% block content %}
                    {% endblock content %}
                </div>
            </div>
        </div>
        <!-- End your project here-->

        <!-- MDB -->
        <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
    </body>
</html>

myenv/kebapbuilder/kebapbuilder/templates/kebapbuilder/order_detail.html
{% extends 'kebapbuilder/base.html' %} 

{% block title %}Neue Bestellung{% endblock %}

{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_div }}

    {{ form.non_field_errors }}
    <!-- Name input -->
    <div class="form-outline mb-4">
        {{ form.person.errors }}
        <label class="visually-hidden" for="inlineFormSelectPref">Name</label>
        {{ form.person }}
    </div>
</form>
{% endblock content %}

myenv/kebapbuilder/kebapbuilder/templates/kebapbuilder/order_list.html
{% extends 'kebapbuilder/base.html' %} 

{% block title %}Bestellungen{% endblock %}

{% block content %}
<a type="button" class="btn btn-primary btn-rounded mb-2" href="{% url 'kebapbuilder:add' %}"> Person hinzufügen </a>
<table class="table align-middle mb-0 bg-white">
    <thead class="bg-light">
        <tr>
            <th>Name</th>
            <th>Typ</th>
            <th>Sorte</th>
            <th>Extrawünsche</th>
            <th>Status</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for order in order_list %}
        <tr>
            <td>{{order.person.firstname}} {{order.person.lastname}}</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

myenv/kebapbuilder/polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote" />
</form>

myenv/kebapbuilder/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" href="{% static 'polls/style.css' %}">

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

myenv/kebapbuilder/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>